version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3901
    ports:
      - "3901:3901"
    restart: unless-stopped
    networks:
      - churchill_network
      
networks:
  churchill_network:
    external: true
    name: churchill_network
